#!/usr/bin/env fish

if test (uname) != "Linux"
    echo "You need to run this script on Linux, preferrably Arch"
end

sudo update-pacman-db
yaourt -Syua --force --needed --noconfirm
sudo pkgfile -u
sudo pip install -U (pip list | pawk f[0])
sudo pip2 install -U (pip2 list | pawk f[0])
fisher update
fish_update_completions
plug-update

if exists apm
    apm upgrade -c false
else
    apm-beta upgrade -c false
end

sudo npm -g i (npm -g outdated --depth=0 --parseable | cut -d: -f2)

echo 'Cleaning up.'
yaourt -Scc --noconfirm
yaourt -Rscun (yaourt -Qdtt --noconfirm)
if exists rmshit
    echo y | rmshit
end

