#!/usr/bin/env fish

if test (uname) != "Linux"
    echo "You need to run this script on Linux, preferrably Arch"
end

sudo update-pacman-db
yaourt -Syua --force --needed --noconfirm
sudo pkgfile -u
sudo pip install -U (pip list | pawk f[0])
sudo pip2 install -U (pip2 list | pawk f[0])
fisher update
fish_update_completions
plug-update

if exists apm
    apm upgrade -c false
end

if exists apm-beta
    apm-beta upgrade -c false
end

echo 'Cleaning up.'
yaourt -Scc --noconfirm
yaourt -Qdtt --noconfirm
if exists rmshit
    echo y | rmshit
end

printf '\n\n'
echo "Remember to upgrade your npm packages! :)"

