#!/usr/bin/env fish

if test (uname) != "Linux"
    echo "You need to run this script on Linux, preferrably Arch"
end

if test (count $argv) -gt 0
    if test $argv[1] = "-l"
        echo "Pacman:"
        checkupdates; and checkupdates-aur

        echo -e "\nPip:"
        pip list --user -o

        echo -e "\nPip 2:"
        pip2 list --user -o
    end
    exit 0
end

sudo update-pacman-db
yaourt -Syua --needed --noconfirm
sudo pkgfile -u
pip install  --user -U (pip --user list | pawk f[0])
pip2 install --user  -U (pip2 --user list | pawk f[0])
fisher update
fish_update_completions
update-plug

if exists apm
    apm upgrade -c false
end

if exists apm-beta
    apm-beta upgrade -c false
end

if exists npm
    set -l pkgs (npm -g outdated --depth=0 --parseable | cut -d: -f4)
    if test (count $pkgs) -gt 0
        sudo npm -g i $pkgs
    end
end

echo 'Cleaning up.'
yaourt -Scc --noconfirm
yaourt -Rscun (yaourt -Qdtt --noconfirm)
if exists rmshit
    echo y | rmshit
end

