#!/usr/bin/env fish

function get_commit_name
  g log --format=%B -n 1 $argv[1]
end

function main
  set git_hash $argv[1]

  if test -z "$git_hash"
    set git_hash HEAD
  end

  set start_commit "$git_hash~0"
  set end_commit "$git_hash~1"

  set commit_name (get_commit_name $start_commit)
  echo "Viewing \"$commit_name\"..."
  set result (read -p 'echo "Continue? ([y] / n): "')

  if test "$result" != 'n'
    g diff $end_commit...$start_commit
  end
end

main $argv


