#!/usr/bin/env fish

set -l files **/*.tar* **/src **/pkg

if test (count $files) -gt 0
    echo "Removing "{(count $files)}" files!"
    rm -rf $files
    echo "Done!"
else
    echo "No files!"
end


