#!/usr/bin/env fish

set image_name 'resume-builder'
set resume_dir $DOTFILES/share/latex/resume
set resume_file $DOTFILES/resume.pdf
set staged_files (git diff --name-only --cached)

function is_file_staged
  echo $staged_files | rg -q $argv
end

function build_resume
  if not docker images | rg -q $image_name
    echo "Building image '$image_name'"
    docker build --rm -t $image_name $resume_dir
  end

  docker run --rm -i -v $resume_dir:/resume $image_name
end

if is_file_staged resume.tex && not is_file_staged resume.pdf
  echo 'Resume updated but compiled pdf is not staged'
  echo 'Building resume.pdf'

  build_resume
  cp $resume_dir/build/resume.pdf $resume_file
  rm -rf $resume_dir/build

  git add $resume_file
end
