#!/usr/bin/env fish

if test (uname) != "Linux"
    echo "You need to run this script on Linux"
end

if test -n "$EDITOR"
    eval $EDITOR $HOME/.config/i3/config
else
    echo "Editor environment variable is not set"
    exit -1
end

