#!/usr/bin/env fish

if test ! -f /usr/bin/nvim -a ! -f /usr/local/bin/nvim
    echo "NeoVim not installed!"
    exit -1
end

eval $EDITOR +PlugInstall +PlugUpdate +PlugUpgrade +PlugClean! +qall

rm -fv ~/.config/nvim/autoload/plug.vim.old

