#!/usr/bin/env fish

if test ! -f /usr/bin/nvim
    echo "NeoVim not installed!"
    exit -1
end

eval $EDITOR +PlugInstall +PlugUpdate +PlugUpgrade +PlugClean! +qall

set -l old_plug ~/.config/nvim/autoload/plug.vim.old
rm -fv $old_plug

