#!/usr/bin/env fish

if test ! -f ~/.shittyfiles
    echo "Shitty files list missing!"
    echo "Create shitty files in '~/.shittyfiles'"
    exit 0
end

set -l shitty_files (cat ~/.shittyfiles)
set -l files_to_delete

for file in $shitty_files
    set -l expanded_file (eval "echo $file")
    if test -e $expanded_file
        set files_to_delete $files_to_delete $expanded_file
    end
end

set -l len (count $files_to_delete)

if test $len -eq 0
    echo "No shitty files found!"
    exit 0
end

echo "Found $len shitty files:"

for file in $files_to_delete
    printf "  $file\n"
end

echo "Deleting in 1 second..."
sleep 1

for file in $files_to_delete
    rm -rfv $file
end

