#!/usr/bin/env fish

sudo update-pacman-db
yaourt -Syua --force --needed --noconfirm
sudo pkgfile -u
sudo pip install -U (pip list | pawk f[0])
sudo pip2 install -U (pip2 list | pawk f[0])
fisher update
fish_update_completions
plug-update

echo "Remember to upgrade your npm and apm packages! :)"

