#!/usr/bin/env fish

# Checks if the user is root
if test (id -u) -ne 0
    echo "Must be root to run"
    exit -1
end

# Gets a list of mirrors sorted by rate using n threads
reflector -c US --verbose --threads (nproc) --sort rate --save /etc/pacman.d/mirrorlist

